# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_auto_20160604_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='signo',
        ),
    ]
